version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: docusec-postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docusec-network

  backend:
    build: .
    container_name: docusec-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - uploaded_files_data:/app/uploaded_files
      - ./ml:/app/ml
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - docusec-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  uploaded_files_data:
    driver: local

networks:
  docusec-network:
    driver: bridge
